# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        versions: [0.239.x_obf, 0.239.x_p_obf, base, base_proto2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run build of version ${{ matrix.versions }}
      run: |
        # Install dependencies...
        sudo apt-get install clang-format
        pushd /tmp
        wget https://github.com/protocolbuffers/protobuf/releases/download/v21.1/protoc-21.1-linux-x86_64.zip
        unzip protoc-21.1-linux-x86_64.zip
        popd
        export PATH=/tmp/bin:$PATH
        # Run's
        chmod +x ./compile_base.py
        ./compile_base.py -l cpp -v ${{ matrix.versions }}
        clang-format -i -style file $(find base -name "v${{ matrix.versions }}.proto")
        # git diff --exit-code
